# Stage 1: Build the Java application
FROM maven:3.8.4-openjdk-11 AS build-stage
WORKDIR /app

COPY pom.xml .

RUN mvn dependency:go-offline -B

COPY src ./src

RUN mvn package

# Stage 2: Create the runtime image
FROM adoptopenjdk/openjdk11:jre-11.0.12_7-alpine AS runtime-stage

WORKDIR /app

COPY --from=build-stage /app/target/my-app.jar ./app.jar

EXPOSE 8080

CMD ["java", "-jar", "app.jar"]
